<!doctype html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=utf-8" />
  <!--Begin Style Block-->
  <style type="text/css">
    body {color: #4a4542; background: #f5f1e4; border-top: 5px solid red; margin: 0; padding: 0; font-family: Helvetica Neue, Helvetica, Arial, Verdana, sans-serif;}
    #sweepstakesRules {width: 70%; margin: 0 auto;}
    h1, h2, h3 {font-weight: normal;}
    a:link {color: red; text-decoration: none;}
  </style>
  <!--End Style Block-->
  <title>Nestl&eacute; Purina PetCare Sweepstakes</title>
</head>

<body>
  <div id="sweepstakesRules">
    <h1>Nestl&eacute; Purina PetCare Sweepstakes</h1>
    <h2>OFFICIAL SWEEPSTAKES RULES</h2>
    <h3>NO PURCHASE OR PAYMENT OF ANY KIND NECESSARY TO ENTER OR WIN.  A PURCHASE WILL NOT INCREASE YOUR CHANCES OF WINNING</h3>
    <p>The Nestl&eacute; Purina Sweepstakes ("Sweepstakes") starts at 9:00 a.m. CT on February 12, 2013 and ends at 8:59:59 a.m. CT on August 6, 2013 (the "Sweepstakes Period").</p>
    <p><strong>ELIGIBILITY</strong>: This Sweepstakes is only open to legal residents of the 50 United States and D.C., who are 18 years of age or older (19 years of age or older in AL and NE) at the time of entry and who are enrolled (at the time of entry) as an undergraduate or graduate student at an accredited college or university in the United States. This Sweepstakes is not open to the general public.  Employees of Nestl&eacute; Purina PetCare Company ("Sponsor"), its parent, subsidiary companies, affiliates, advertising and promotional agencies, and the independent judging organization, and the immediate family (spouse, parent, child, sibling and their respective spouses or "step" of each) and household members of such employees are not eligible. All federal, state and local laws and regulations apply to participation in the Sweepstakes. Void where prohibited by law.</p>
    <p><strong>HOW TO ENTER</strong>: Access the Nestl&eacute; Purina Sweepstakes application on the Nestl&eacute; Purina Careers page on Facebook at http://www.facebook.com/NestlePurinaCareers (the "Application") during the Sweepstakes Period.  To access the Application, you must 'like' the Nestl&eacute; Purina Careers page on Facebook.  To enter, complete the entry form by entering your first and last name, email address, college major, expected graduation date and the name of your college or university (optional) and indicate whether you are undergraduate or graduate student.   There will be two separate entry periods, as set forth in the table below.  You may enter the Sweepstakes one time per entry period.  Entry must be received by 8:59:59 a.m. CT on the last day of each entry period to be eligible for entry into the random drawing for that entry period.  Limit one entry per person/e-mail address, excluding Referral Entries (see below).</p>
    <p>You may share the Sweepstakes with your friends, who are eligible to enter, via one of the several means of sharing offered on the Application. You may not attempt to induce others to enter the Sweepstakes through the use of any incentive or promotion. Any use of automatic methods of entry by any party will void all such Applications and will result in the Application in question being declared ineligible and disqualified from the Sweepstakes. Any attempt by you and/or your friends and/or community to enter each entry period more than one time per person/e-mail address using "Bot" technology and/or any other fraudulent mechanism, as determined by Sponsor in its sole discretion, shall give Sponsor the right to disqualify the Application in Sponsor's reasonable discretion.</p>
    <p>Each time someone uses the link in your post to access the Application and enter the Sweepstakes, you will receive one additional entry into the Sweepstakes (a "Referral Entry"). You may only share the sweepstakes with people you know personally.  Persons submitting a Referral Entry must also meet the eligibility requirements as set forth above. Limit of ten (10) Referral Entries per person.</p>
    <p>Sponsor is not responsible for late or incomplete entries.  Participation constitutes your full and unconditional agreement to these Official Sweepstakes Rules and Sponsor and Administrator's decisions, which are final and binding in all matters related to the Sweepstakes.</p>
    <p>This Sweepstakes is in no way sponsored, endorsed or administered by Facebook.  You are providing your information to Sponsor and not to Facebook.  Questions regarding this Sweepstakes should be directed to Administrator at: <a href="mailto:purina@pfcfulfills.com">purina@pfcfulfills.com</a>, not to Facebook.</p>
    <p><strong>PRIZES:</strong> Two (2) Prizes (one per drawing): $1,500</p>
    <p>Prizes will be awarded in the form of a check payable to the winner and are not transferable.  Total value of all available prizes: $3,000.00.  All applicable federal, state and local taxes, are solely the responsibility of the winner.</p>
    <p><strong>DRAWINGS:</strong> A random drawing will be conducted from among all eligible entries received prior to the entry deadline for the drawing to select one (1) winner per drawing.  The entry deadline for Drawing #1 is 8:59:59 a.m. CT on May 7, 2013.  Drawing number #1 will be held on or about May 7, 2013, after all eligible entries have been received.  The entry deadline for Drawing #2 is 8:59:59 a.m. CT on August 6, 2013.  Drawing number #2 will be held on or about August 6, 2013, after all eligible entries have been received.  Odds of winning depend on the number of eligible entries received by the entry deadline for each drawing. Non-winning entries from Drawing #1 will be included in Drawing #2.  Limit one prize per person. Winning a prize is contingent upon fulfilling all requirements set forth herein.</p>
    <p><strong>RELEASES AND GENERAL CONDITIONS:</strong> Potential winners will be notified by email,  and will be required to execute and return an affidavit of eligibility with supporting information, a liability release and, where lawful, a publicity release within seven (7) days of Sponsor's sending of notice (regardless of whether the notified winner acknowledges receipt of notice). Verification of current college enrollment status will be required.  If such documents are not returned within the specified time period, the prize notification is returned as undeliverable, or the potential winner is ineligible or otherwise not in compliance with these Official Sweepstakes Rules, an alternate winner may be selected randomly from remaining non-winning entries. Sponsor is not responsible for any change to your email, mailing address and/or telephone number.</p>
    <p>By entering the Sweepstakes, participants agree that the Sponsor, its parent, subsidiary and affiliated companies, their respective officers, directors, agents, and employees are not responsible for and shall not be liable for: (1) any incorrect or inaccurate information associated with the Sweepstakes (2) any errors, omissions, interruptions, deletions, defects, or delays in operation,  or in any materials associated with the  Sweepstakes;  (3) any design, typographical or other errors in any materials associated with the Sweepstakes; (4) garbled, incomplete, damaged, misdirected, late, lost, undelivered, or unprocessed entries; or (5) any condition caused by events beyond the control of the Sponsor which may cause the Sweepstakes to be disrupted or corrupted.</p>
    <p>Sponsor may prohibit you from participation in the Sweepstakes if Sponsor determines that you have acted in a manner that affects the administration, security, fairness or proper play or conduct of the Sweepstakes in any way, with an intent to annoy, threaten or harass any other participants or the Sponsor.   Sponsor reserves the right, in its sole discretion, to modify, cancel, terminate, or suspend all or any portion of this Sweepstakes should fraud,  or other causes beyond the control of the Sponsor and its agencies corrupt or affect the administration, security, fairness or proper play or conduct of the Sweepstakes.  In the event of cancellation, Sponsor will award the prize in a drawing from all eligible, non-suspect entries received prior to cancellation as set forth herein.</p>
    <p>By entering, entrants agree, and by accepting a prize, winner agrees to release and hold Nestl&eacute; Purina PetCare Company,  its parent, subsidiaries, affiliates, directors, employees, agents, successors and/or assigns and their advertising and promotional agencies ("Sweepstakes Parties") harmless from any damage, loss or liability to person or property, due in whole or part, directly or indirectly, by reason of participation in this Sweepstakes or the acceptance, possession, use or misuse of prize or travel in connection therewith.  Sponsor assumes no responsibility for any third party's failure to act in accordance with Sponsor's instructions pertaining to the implementation of this Sweepstakes.</p>
    <p>Except where prohibited by law, acceptance of a prize constitutes permission to use the winner's name, biographical information, and/or likeness for purposes of advertising and promotion in all media, including on-line worldwide, without limitation or further compensation.</p>
    <p>By entering this Sweepstakes, the entrant gives its consent for Sponsor to deliver personal information to the Sweepstakes administrator as required for the purpose of administering the Sweepstakes.  Information will be used in accordance with Sponsor's online privacy policy.  For information regarding Sponsor's online privacy policy go to www.purina.com and click on "Privacy Policy".</p>
    <p>By participating, participants agree that all issues and questions concerning the construction, validity, interpretation and enforceability of these Official Sweepstakes Rules, participant's rights and obligations, or the rights and obligations of the Sponsor in connection with the Sweepstakes, shall be governed by, and construed in accordance with, the laws of State of Missouri, without giving effect to any choice of law or conflict of law rules, and participants consent to the jurisdiction and venue of the federal, state and local courts located in  St. Louis, MO.  Any and all disputes, claims and causes of action arising out of or connected with this Sweepstakes, or any prize awarded, shall be resolved individually, without resort to any form of class action.  Any and all claims, judgments and awards shall be limited to actual out-of-pocket costs incurred, including costs associated with participating in this Sweepstakes, but in no event attorney's fees.</p>
    <p><strong>WHO WON:</strong> The names of the confirmed Prize Winners will be posted on the Nestl&eacute; Purina Careers Facebook page at <a href="https://www.facebook.com/NestlePurinaCareers?ref=ts">https://www.facebook.com/NestlePurinaCareers?ref=ts</a>. To receive the list of winners by email, send an email with "Sweepstakes Winners List" in the subject line to: <a href="mailto:careers@purina.nestle.com">careers@purina.nestle.com</a>.  Requests must be received by September 1, 2013.</p>
    <p>Sponsor:   Nestl&eacute; Purina PetCare Company, Checkerboard Square, St. Louis, MO  63164. Administrator: Promotion Fulfillment Center, 311 21st Street, Camanche, IA 52730</p>
	</div><!-- sweepstakes rules -->
</body>
</html>